class AppConstants {
  static String myDawaiWalaDescription =
      "Welcome to My DawaiWala, your go-to destination for fast and reliable medicine delivery. We are a health-tech start-up driven by the mission to make healthcare more accessible and convenient for everyone. Our goal is to ensure you never have to wait long for your medications, delivering your prescriptions in as little as 20 minutes—right to your doorstep.\n\n"
      "At My DawaiWala, we understand that when it comes to health, time is of the essence. That's why we've built an efficient, user-friendly service powered by our in-house pharmacy and a trusted network of delivery partners. Whether it's an urgent prescription, daily vitamins, or skincare essentials, we've got you covered—quickly and reliably.\n\n"
      "Our platform allows you to do more than just order medicines. You can now shop online for a wide range of healthcare products, including:\n"
      "➢ Medicines from leading pharmaceutical brands\n"
      "➢ Milk powders and Protein powders for nutritional needs\n"
      "➢ Injections and other specialized treatments\n"
      "➢ Liquid energy drinks to fuel your day\n"
      "➢ First aid kits for emergencies\n"
      "➢ The latest in Skin, Hair, and Health care essentials from trusted brands like Cipla, Sun Pharma, and Torrent Pharma.\n\n"
      "Whether you're looking for daily health supplements or quick access to prescribed medicines, we make it easy for you to get everything you need in one place.\n\n"
      "Why Choose My DawaiWala?\n"
      "• Fastest Delivery: Receive your order within 20 minutes.\n"
      "• All-in-One Platform: Shop for medicines, health essentials, and more—right from the app.\n"
      "• Convenient Ordering: Place orders via our app, website, or WhatsApp.\n"
      "• Trusted Brands: Access products from leading names in the pharmaceutical and healthcare industry.\n"
      "• Reliability: Our certified pharmacy partners and professional delivery team ensure the highest quality service.\n\n"
      "With My DawaiWala, your health and convenience are our top priorities. Download the app today and experience healthcare at your fingertips—delivered faster and more efficiently than ever.\n\n"
      "'My DawaiWala' is owned & managed by 'SwiftMeds Pharma Private Limited'.";

  static String returnPolicyDescription =
      "At My DawaiWala—proudly managed and operated under the stewardship of SwiftMeds Pharma Private Limited—we are committed to ensuring that you receive the correct medicines and healthcare products with every order. Our team takes pride in processing your orders with utmost accuracy. However, we recognize that unforeseen circumstances may arise where a return, refund, or cancellation becomes necessary. In such cases, we are here to assist you in resolving any issues promptly.\n\n"
      "We strongly recommend that all items be thoroughly inspected at the time of delivery to ensure your satisfaction and to avoid any inconvenience later.\n\n"
      "Return Policy:\n"
      "In the event that you receive an incorrect or damaged product, we provide a hassle-free return process via the app. Returns are accepted under the following circumstances:\n"
      "- Wrong Product Delivered: If the product you receive does not match your order.\n"
      "- Damaged or Defective Products: If the product is damaged or defective upon delivery.\n"
      "- Delayed Orders: If your order is delayed by more than 40 minutes from the estimated delivery time communicated to you during order placement.\n\n"
      "Conditions for Return:\n"
      "To facilitate a smooth return process, the following conditions must be met:\n"
      "1. Products must be returned in their original packaging, with labels, barcodes, price tags, and serial numbers intact.\n"
      "2. The batch number of the product must match the number listed on the invoice.\n"
      "3. Returned products must be unused. Opened strips of medicine or bottles are not eligible for return.\n"
      "4. The return request must include clear evidence (e.g., photographs or videos) showing the defect or discrepancy.\n"
      "5. If the defect is covered under the manufacturer’s warranty, the product can be returned under warranty conditions.\n\n"
      "Non-Returnable Items:\n"
      "Certain products are not eligible for return due to their nature or health regulations. These include:\n"
      "- Temperature-Controlled Medicines: Vials, injections, pen-fills, vaccines, or other cold-storage medications.\n"
      "- Baby Care Products: Diapers, breast pumps, bottle nipples, etc.\n"
      "- Food and Nutrition: Health supplements, nutritional drinks, baby food.\n"
      "- Healthcare Devices: Glucometer lancets, surgical instruments, health monitors.\n"
      "- Personal Care Items: Oral care (toothbrushes, toothpaste), feminine hygiene products (sanitary pads, menstrual cups), and shaving or hair removal products.\n"
      "- Sexual Wellness Products: Condoms, lubricants, pregnancy kits.\n"
      "- Wearable Medical Devices: Any partially used items like bandages, knee caps, or medical wearables.\n"
      "- COVID Masks: Unpacked N95 or surgical masks cannot be returned.\n\n"
      "Refund Policy:\n"
      "For returned products that are deemed eligible, refunds will be processed within 7 business days following the verification of the returned items. Refunds will be credited to the original payment method as follows:\n"
      "- Online Payment: Refunds will be issued directly to the source account (e.g., wallet, bank card).\n"
      "- Cash on Delivery (COD): Refunds for COD orders will be issued via direct bank transfer, subject to verification.\n\n"
      "Please note that after the refund has been initiated, it may take additional time for the refunded amount to reflect in your account, depending on your financial institution’s policies.\n\n"
      "Cancellation Policy:\n\n"
      "Customer-Initiated Cancellations:\n"
      "- You can cancel any order free of charge before it is accepted by our system.\n"
      "- Once the order is confirmed and accepted, cancellations initiated by the customer will not be permitted.\n\n"
      "Company-Initiated Cancellations:\n"
      "Under certain conditions, My DawaiWala may need to cancel your order:\n"
      "- If the product is out of stock or unavailable.\n"
      "- If there are inaccuracies in pricing or product information.\n"
      "- If the order is classified as a bulk order or exceeds quantity limits, which could include multiple orders for the same product or items not intended for personal use.\n\n"
      "In such cases, any payment made will be fully refunded.\n\n"
      "Bulk Orders and Other Limitations:\n"
      "To maintain fairness and avoid misuse of our platform, My DawaiWala reserves the right to cancel orders classified as bulk orders or those that exceed standard purchase limitations. Bulk orders may include:\n"
      "- Multiple orders for the same product delivered to the same address.\n"
      "- Orders placed for commercial purposes rather than personal use.\n"
      "- Orders with incorrect or incomplete delivery details.";
}
